module.exports = {
  DESCRIPTION: process.env.DESCRIPTION,
  FYNDIQ_APIURL: process.env.FYNDIQ_APIURL,
  FYNDIQ_USERNAME: process.env.FYNDIQ_USERMAME,
  FYNDIQ_APIKEY: process.env.FYNDIQ_APIKEY,
  FYNDIQ_SUFFIX: process.env.FYNDIQ_SUFFIX,
  ONGOING_APIURL: process.env.ONGOING_APIURL,
  ONGOING_GOODSOWNERID: process.env.ONGOING_GOODSOWNERID,
  ONGOING_USERNAME: process.env.ONGOING_USERNAME,
  ONGOING_PASSWORD: process.env.ONGOING_PASSWORD,
  SLACK_WEBHOOK: process.env.SLACK_URL,
};
